# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(verbose_name='date due')),
                ('complete_date', models.DateTimeField(verbose_name='date complete')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Person')),
            ],
        ),
    ]
